"""add client key to form fields

Revision ID: 5d07f7b679d3
Revises: 805fc2188d93
Create Date: 2026-08-21 16:11:36.835974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d07f7b679d3'
down_revision: Union[str, Sequence[str], None] = '805fc2188d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('client_key', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uq_form_field_client_key', 'form_fields', ['form_id', 'client_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_form_field_client_key', 'form_fields', type_='unique')
    op.drop_column('form_fields', 'client_key')
    # ### end Alembic commands ###
