"""create form response tables

Revision ID: 6b35184411c8
Revises: 5d07f7b679d3
Create Date: 2026-08-21 19:11:13.724302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b35184411c8'
down_revision: Union[str, Sequence[str], None] = '5d07f7b679d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_form_id'), 'form_responses', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_responses_id'), 'form_responses', ['id'], unique=False)
    op.create_index(op.f('ix_form_responses_user_id'), 'form_responses', ['user_id'], unique=False)
    op.create_table('response_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'field_id', name='uq_response_field')
    )
    op.create_index(op.f('ix_response_details_field_id'), 'response_details', ['field_id'], unique=False)
    op.create_index(op.f('ix_response_details_id'), 'response_details', ['id'], unique=False)
    op.create_index(op.f('ix_response_details_response_id'), 'response_details', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_details_response_id'), table_name='response_details')
    op.drop_index(op.f('ix_response_details_id'), table_name='response_details')
    op.drop_index(op.f('ix_response_details_field_id'), table_name='response_details')
    op.drop_table('response_details')
    op.drop_index(op.f('ix_form_responses_user_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_form_id'), table_name='form_responses')
    op.drop_table('form_responses')
    # ### end Alembic commands ###
